intellij_idea_product_code=IIU
intellij_idea_releases_api_base_uri=https://data.services.jetbrains.com/products/releases
intellij_idea_plugins_api_base_uri=https://plugins.jetbrains.com/pluginManager
