# Base packages (core tools installed first)
base_packages=()
base_packages+=("homebrew")
base_packages+=("vim")
base_packages+=("bash")
base_packages+=("bash_it")
base_packages+=("git")

# Required packages (standard tools)
required_packages=()
required_packages+=("bats")
required_packages+=("dockutil")
required_packages+=("gcc")
required_packages+=("gradle")
required_packages+=("intellij_idea")
required_packages+=("iterm")
required_packages+=("java")
required_packages+=("jenv")
required_packages+=("jq")
required_packages+=("kotlin")
required_packages+=("ktlint")
required_packages+=("llm_context")
required_packages+=("maccy")
required_packages+=("node")
required_packages+=("pip")
required_packages+=("pycharm")
required_packages+=("python")
required_packages+=("rectangle")
required_packages+=("uv")

# Supported Node packages (installed via npm)
supported_node_packages=()

# Supported Python packages (installed via pip)
supported_pip_packages=()
