name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/cancel.yml
      - .gitignore
      - LICENSE
      - README.md

jobs:
  build:
    uses: opengoodio/central-workflows/.github/workflows/bash-bats-build.yml@main
