name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/*
      - .gitignore
      - LICENSE
      - README.md

jobs:
  build:
    uses: opengood-aio/central-workflows/.github/workflows/bash-bats-build.yml@main
