name: Lint
# description:
# - Runs Bash Super Linter providing source code quality and review information
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Create release')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
